/** Node-only staging entry. Do not re-export from the browser entry. */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, lstatSync, unlinkSync } from 'node:fs';
import { resolve, dirname, sep, isAbsolute } from 'node:path';
import { unzipSync } from 'fflate';
import { assertPackPath, validateManifest } from '../assets/manifest';
import type { CreditEntry, PackCell, PackFile, PackManifest } from '../assets/manifest';
export interface StageFile {from:string;to:string;sha256?:string}
export interface StagePlan {id:string;release:string;three:'0.186.1';out:string;force?:boolean;models:{id:string;to:string}[];data:Record<string,string>;files:StageFile[];credits?:CreditEntry[];cells?:PackCell[];source?:Record<string,unknown>}
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
function within(dir:string,path:string):string{assertPackPath(path);const root=resolve(dir),target=resolve(root,path);if(!target.startsWith(root+sep))throw new Error(`Path outside output: ${path}`);let parent=target;while(parent!==root){if(existsSync(parent)&&lstatSync(parent).isSymbolicLink())throw new Error(`Symbolic link in output: ${path}`);parent=dirname(parent);}if(existsSync(root)&&lstatSync(root).isSymbolicLink())throw new Error(`Symbolic output: ${root}`);return target;}
export function readZip(path:string,expected?:{bytes:number;sha256:string}):Map<string,Uint8Array>{const bytes=readFileSync(path);if(expected&&(bytes.length!==expected.bytes||hash(bytes)!==expected.sha256))throw new Error(`Archive integrity mismatch: ${path}`);let entries:ReturnType<typeof unzipSync>;try{entries=unzipSync(bytes);}catch(cause){throw new Error(`Cannot read zip: ${path}`,{cause});}const result=new Map<string,Uint8Array>();for(const [name,body]of Object.entries(entries)){if(name.endsWith('/'))continue;assertPackPath(name);result.set(name,body);}return result;}
/** Sealed archive receipts may omit their own delivery.json; only explicitly ignored entries are exempt. */
export function verifyArchiveMembers(entries:Map<string,Uint8Array>,files:readonly PackFile[],ignore:ReadonlySet<string>=new Set()):void{const listed=new Set<string>();for(const file of files){assertPackPath(file.path);if(listed.has(file.path))throw new Error(`Duplicate member: ${file.path}`);listed.add(file.path);const b=entries.get(file.path);if(!b)throw new Error(`Missing member: ${file.path}`);if(b.length!==file.bytes||hash(b)!==file.sha256.replace(/^sha256:/,''))throw new Error(`Member integrity mismatch: ${file.path}`);}for(const path of entries.keys())if(!listed.has(path)&&!ignore.has(path))throw new Error(`Extra member: ${path}`);}
function walk(dir:string,prefix=''):string[]{if(!existsSync(dir))return[];const result:string[]=[];for(const entry of readdirSync(dir,{withFileTypes:true})){const path=prefix+entry.name;if(entry.isSymbolicLink())throw new Error(`Symbolic staged entry: ${path}`);if(entry.isDirectory())result.push(...walk(resolve(dir,entry.name),path+'/'));else result.push(path);}return result;}
export function stageFiles(plan:StagePlan):{files:number;bytes:number}{
 if(plan.three!=='0.186.1')throw new Error('Stage plan three pin must be 0.186.1');const out=resolve(plan.out),copies=new Map<string,Uint8Array>(),files:PackFile[]=[];for(const file of plan.files){assertPackPath(file.to);if(file.to==='pack.json'||file.to==='SHA256SUMS'||copies.has(file.to))throw new Error(`Reserved or duplicate output: ${file.to}`);if(!isAbsolute(file.from))throw new Error(`Source must be absolute: ${file.from}`);const from=resolve(file.from);if(from===out||from.startsWith(out+sep))throw new Error(`Source is inside output: ${from}`);const b=readFileSync(from),sha256=hash(b);if(file.sha256&&file.sha256.replace(/^sha256:/,'')!==sha256)throw new Error(`Source integrity mismatch: ${file.from}`);copies.set(file.to,b);files.push({path:file.to,bytes:b.length,sha256});}
 const manifest:PackManifest&{source?:Record<string,unknown>}={schema:'kiln.scene-pack/1',id:plan.id,release:plan.release,three:plan.three,models:plan.models.map(m=>({id:m.id,path:m.to})),data:plan.data,files};if(plan.credits)manifest.credits=plan.credits;if(plan.cells)manifest.cells=plan.cells;if(plan.source)manifest.source=plan.source;validateManifest(manifest);
 copies.set('pack.json',new TextEncoder().encode(JSON.stringify(manifest,null,2)+'\n'));copies.set('SHA256SUMS',new TextEncoder().encode(files.map(f=>`${f.sha256}  ${f.path}\n`).join('')));
 // All validation occurs before the first write; partial invalid outputs never overwrite an existing pack.
 for(const [path,b]of copies){const target=within(out,path);if(existsSync(target)&&hash(readFileSync(target))!==hash(b)&&!plan.force)throw new Error(`Existing output differs: ${path} (use --force)`);}
 const extras=walk(out).filter(p=>!copies.has(p));if(extras.length&&!plan.force)throw new Error(`Unexpected existing output: ${extras[0]} (use --force)`);
 for(const path of extras)unlinkSync(within(out,path));
 for(const [path,b]of copies){const target=within(out,path);mkdirSync(dirname(target),{recursive:true});if(!existsSync(target)||hash(readFileSync(target))!==hash(b))writeFileSync(target,b);}
 const checked=verifyStaged(out);if(!checked.ok)throw new Error(checked.problems.join('\n'));return{files:files.length,bytes:files.reduce((n,f)=>n+f.bytes,0)};
}
export function verifyStaged(dir:string):{ok:boolean;problems:string[]}{const problems:string[]=[];let manifest:PackManifest;try{manifest=validateManifest(JSON.parse(readFileSync(within(dir,'pack.json'),'utf8')));}catch(error){return{ok:false,problems:[`pack.json: ${String(error)}`]};}for(const f of manifest.files)try{const b=readFileSync(within(dir,f.path));if(b.length!==f.bytes)problems.push(`${f.path}: byte length mismatch`);if(hash(b)!==f.sha256)problems.push(`${f.path}: SHA-256 mismatch`);}catch(error){problems.push(`${f.path}: ${String(error)}`);}const sums=manifest.files.map(f=>`${f.sha256}  ${f.path}\n`).join('');try{if(readFileSync(within(dir,'SHA256SUMS'),'utf8')!==sums)problems.push('SHA256SUMS: manifest mismatch');}catch(error){problems.push(`SHA256SUMS: ${String(error)}`);}try{const expected=new Set(['pack.json','SHA256SUMS',...manifest.files.map(f=>f.path)]);for(const p of walk(dir))if(!expected.has(p))problems.push(`${p}: extra staged file`);}catch(error){problems.push(String(error));}return{ok:!problems.length,problems};}
