import { build } from 'vite';
import { cp, readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { sceneStandaloneConfig, sourcePath } from '../packages/scene-kit/src/build';
const root=resolve(import.meta.dir,'..'),out=resolve(root,'packages/scene-kit/dist/consumer');
const compiler=Bun.spawnSync(['node',resolve(root,'node_modules/typescript-6/bin/tsc'),'--noEmit','-p',resolve(root,'packages/scene-kit/consumer/tsconfig.json')],{cwd:root,stdout:'pipe',stderr:'pipe'});
const output=new TextDecoder().decode(compiler.stdout)+new TextDecoder().decode(compiler.stderr);
if(compiler.exitCode!==0)throw new Error(output);
const config=sceneStandaloneConfig({root:resolve(root,'packages/scene-kit/consumer'),outDir:out,mode:'public'});
const aliases=(config.resolve!.alias as {find:RegExp;replacement:string}[]);
aliases.push({find:/^@kiln-scenes\/scene-kit$/,replacement:sourcePath(new URL('../packages/scene-kit/src/index.browser.ts',import.meta.url))});
await build({...config,configFile:false});
await cp(resolve(root,'packages/scene-kit/demo/staged/assets'),resolve(out,'assets'),{recursive:true});
const graph=JSON.parse(await readFile(resolve(out,'bundle-modules.json'),'utf8')) as {modules:string[]};
const packages=new Set(graph.modules.filter(id=>/[\\/]node_modules[\\/]three[\\/]/.test(id)).map(id=>id.replace(/([\\/]node_modules[\\/]three)[\\/].*$/,'$1')));
if(packages.size!==1)throw new Error(`Expected one three package in source consumer; got ${packages.size}`);
await mkdir(resolve(root,'evidence/m1'),{recursive:true});
const result={typescript:'6.0.3',sourceAlias:true,dedupe:config.resolve?.dedupe,threeCopies:packages.size,threePaths:[...packages],typecheck:'pass'};
await writeFile(resolve(root,'evidence/m1/site-compat.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
