import {readRuntimeBytes} from './runtime-transport.mjs';
import {createRigidClipPlayback} from './runtime/fleet-v2/rigid-playback.mjs';import {createFormationIdleRoster} from './formation-roster.mjs';
export async function createFormationIdlePlayback(T,human,units,sourceHash,routeRecordIdentity,{poseTextures=null,motionBindings=null}={}){
 const base=new URL('./runtime/formation-idle-v2/',import.meta.url),hash=async b=>'sha256:'+Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),v=>v.toString(16).padStart(2,'0')).join(''),manifest=await(await fetch(new URL('manifest.json',base))).json();if(manifest.schema!=='troy.formation-idle-runtime/1')throw Error('Invalid formation idle manifest');
 const read=async file=>{const b=await readRuntimeBytes(new URL(file,base));if(await hash(b)!==manifest.files[file])throw Error('Formation idle identity mismatch '+file);return b;};
 const [json,bytes,boundBytes]=await Promise.all([read('bank.json'),read('transforms.bin'),read('bounds.json')]),record=JSON.parse(new TextDecoder().decode(json)),boundRecord=JSON.parse(new TextDecoder().decode(boundBytes));if(record.sourceHashes['output/regroup-packed-01/record.json']!==routeRecordIdentity||record.source.sha256!==sourceHash||record.data.sha256!==await hash(bytes)||boundRecord.bankSha256!==await hash(json))throw Error('Formation idle source mismatch');
 const sourceActors=new Map(record.actors.map(a=>[a.id,a]));let selectedActors=record.actors;if(motionBindings){const ids=units.flatMap(u=>u.actors);if(motionBindings.length!==ids.length||new Set(motionBindings.map(b=>b.id)).size!==ids.length||ids.some(id=>!motionBindings.some(b=>b.id===id)))throw Error('Formation motion binding roster mismatch');selectedActors=motionBindings.map(b=>{const a=sourceActors.get(b.sourceId);if(!a||b.worldTranslation?.length!==3||!b.worldTranslation.every(Number.isFinite))throw Error('Formation motion binding mismatch');const matrix=new T.Matrix4().makeTranslation(...b.worldTranslation).multiply(new T.Matrix4().fromArray(a.matrix));return {...a,id:b.id,matrix:matrix.toArray()};});}const texturePool=await poseTextures?.register(record.manifest,bytes);const roster=createFormationIdleRoster(units,selectedActors),byId=new Map(selectedActors.map(a=>[a.id,a])),actors=units.flatMap(u=>u.actors.map(id=>{const a=byId.get(id);return {id,clip:a.clip,matrix:new T.Matrix4().fromArray(a.matrix),time:0,loop:true};})),bounds=new Map(boundRecord.bounds.map(b=>[b.name,b])),actorBounds=actors.map(a=>{const b=bounds.get(a.clip);if(!b)throw Error('Missing formation bound');return new T.Box3(new T.Vector3(...b.min),new T.Vector3(...b.max)).applyMatrix4(a.matrix);}),runtime=createRigidClipPlayback(human,{manifest:record.manifest,clips:record.clips,bytes},actors,{texturePool});
 runtime.setActive([]);return {...runtime,roster,actorBounds,positions:actors.map(a=>new T.Vector3().setFromMatrixPosition(a.matrix)),atlasBytes:bytes.byteLength};
}
