import {createResourceScope} from './resource-scope.mjs';
import {resolveWalkingMode} from './walking-mode.mjs';
import {createRigidObjectBounds} from './rigid-object-bounds.mjs';
import {createFormationIdlePlayback} from './formation-idle.mjs';
import {idleRoster} from './idle-roster.mjs';
import {createShoreIdlePlayback} from './shore-idle.mjs';
import {createCrewShoreIdle} from './runtime/crew-idle-v2/shore-idle.mjs';
import {createFleetResources} from './fleet-resources.mjs';
import {createEquipmentArrival} from './runtime/landing-v11/src/ship-equipment.mjs';
import {createArrivalCrew} from './runtime/landing-v11/web/arrival-crew.mjs';
import {createArrivalCrew as createCachedArrivalCrew} from './runtime/crew-block-cached-v1/arrival-crew.mjs';
import {createArrivalCrew as createSubtreeArrivalCrew} from './runtime/crew-v3/arrival-crew.mjs';
import {createArrivalCrew as createDeferredArrivalCrew} from './runtime/crew-v3/arrival-crew-deferred.mjs';
import {createRowingHandoff} from './runtime/landing-v11/src/rowing-handoff.mjs';
import {createOarPlayback} from './runtime/landing-v11/web/oar-playback.mjs';
import {createRigidClipPlayback} from './runtime/fleet-v1/rigid-playback.mjs';
import {createFramedPoseInstances} from './framed-pose-instances.mjs';
import {shoreTime} from './shore-plan.mjs';
import {installFixedNodeLookup} from './fixed-node-lookup.mjs';import {cachePrivateCrewNodes} from './private-crew-cache.mjs';
export async function createShoreFleet(T,{rosters,resources=null,poseMode='subtree',rowAll=false,idleMode='gpu',regroupMode='off',formationIdleMode=regroupMode==='packed'?'gpu':'reference',walkingMode,boundsMode='cached',lateRegroup=false,walkingOffscreenMode='reference',poseDraw='reference',lookupMode='reference'}){
 const scope=createResourceScope();try{
 if(!['reference','cached'].includes(lookupMode))throw Error('Invalid fixed rig lookup mode');
 if(!['reference','shadowSafe'].includes(walkingOffscreenMode))throw Error('Invalid walking offscreen mode');
 if(!['cached','reference','synchronized'].includes(boundsMode))throw Error('Invalid rigid bounds mode');
 if(!['cached','reference','subtree','deferred'].includes(poseMode))throw Error('Invalid crew pose mode');const createCrew=poseMode==='deferred'?createDeferredArrivalCrew:poseMode==='subtree'?createSubtreeArrivalCrew:poseMode==='cached'?createCachedArrivalCrew:createArrivalCrew;
 if(!['off','gpu','reference'].includes(idleMode))throw Error('Invalid shore idle mode');
 if(!['off','reference','packed'].includes(regroupMode))throw Error('Invalid regroup mode');
 if(!['reference','gpu'].includes(formationIdleMode)||(formationIdleMode==='gpu'&&regroupMode!=='packed'))throw Error('GPU formation idle requires packed regroup routes');
 walkingMode=resolveWalkingMode(regroupMode,walkingMode);if(lateRegroup&&regroupMode!=='packed')throw Error('Later regroup requires packed routes');
 const ownResources=!resources;resources??=await createFleetResources(T);if(ownResources)scope.use(resources,'fleet sources');const {data,profile,record,ship:masterShip,human,bytes}=resources;
 const timeline=createEquipmentArrival({profile,queueDuration:data.duration,landedAngle:data.landing.angle}),group=new T.Group(),actors=[],frames=[];group.name='shore-fleet';
 const copy=(a,b)=>a.forEach((n,i)=>{b[i].position.copy(n.position);b[i].quaternion.copy(n.quaternion);b[i].scale.copy(n.scale);});
 const ships=rosters.map(roster=>{
  const ship=masterShip.clone(true);ship.scale.setScalar(1.6);ship.position.fromArray(data.shipPosition);ship.getObjectByName('BoardingPlankPivot').rotation.x=data.landing.angle;ship.getObjectByName('BoardingPlankFold').rotation.x=0;ship.updateMatrixWorld(true);
  const oars=createOarPlayback(T,{ship,rows:data.actors}),crew=createCrew(T,{ship,human,data}),frame=new T.Group(),rendered=ship.clone(true),from=[],to=[];ship.traverse(n=>from.push(n));rendered.traverse(n=>to.push(n));frame.add(rendered);frame.position.fromArray(roster.frame.position);frame.rotation.y=roster.frame.yaw;frame.updateMatrixWorld(true);
  const start=actors.length;actors.push(...crew.actors);for(const a of crew.actors)frames.push(frame.matrixWorld);return {roster,ship,oars,crew,frame,rendered,from,to,start,seated:crew.actors.map(a=>a.root.position.clone()),lastTime:null,last:null,owner:'cpu',rigEvaluations:0,counts:{}};
 });
 if(lookupMode==='cached')for(const s of ships){scope.defer(cachePrivateCrewNodes(s.crew),'crew node cache');scope.defer(installFixedNodeLookup(s.ship),'ship node cache');scope.defer(installFixedNodeLookup(s.rendered),'draw ship node cache');}
 const primary=ships.find(s=>s.roster.id==='ship-1-2')??(regroupMode==='off'||lateRegroup?ships[0]:null);if(!primary)throw Error('Missing primary landing');
 const rowingPlaybacks=new Map();for(const unit of ships)if(rowAll||unit===primary){const runtime=scope.use(createRigidClipPlayback(human,{manifest:record.manifest,clips:record.clips,bytes},unit.crew.actors.map(a=>({id:a.entry.id,matrix:unit.frame.matrixWorld.clone(),clip:`row-${a.entry.row}-${a.entry.side}`,time:0,loop:true})),{texturePool:resources.texturePool}),'rowing playback'),handoff=createRowingHandoff({actors:unit.crew.actors,updateCpu:unit.crew.update,updateOars:t=>unit.oars.update(t),updateGpu:runtime.updateActorPoses});rowingPlaybacks.set(unit,{runtime,handoff});group.add(runtime.group);}
 const baked=rowingPlaybacks.get(primary).runtime,poses=scope.use(createFramedPoseInstances(actors.map(a=>a.root),frames,{mode:poseDraw}),'crew poses'),boats=scope.use(createFramedPoseInstances(ships.map(s=>s.rendered),ships.map(()=>new T.Matrix4()),{mode:poseDraw}),'boat poses');group.add(poses.group,boats.group);let lastTime=-1,activePoseIndices=[],visibleActors=0,visibleShips=0;const poseDirty=new Set(),boatDirtySet=new Set(),actorBounds=actors.map(()=>new T.Box3()),shipBounds=ships.map(()=>new T.Box3());
 const actorReaders=boundsMode!=='reference'?actors.map(a=>createRigidObjectBounds(T,a.root)):null,shipReaders=boundsMode!=='reference'?ships.map(s=>createRigidObjectBounds(T,s.rendered)):null;
 const idleActors=ships.flatMap(s=>s.crew.actors.map(a=>({id:s.roster.actorIds?.[a.entry.id]??s.roster.id+'/'+a.entry.id,matrix:s.frame.matrixWorld.clone(),clip:`idle-${a.entry.row}-${a.entry.side}`,time:0,loop:true}))),idleRuntime=idleMode==='gpu'?await createShoreIdlePlayback(T,human,idleActors,record.source.sha256,{poseTextures:resources.poseTextures}):null,idleReferences=new Map();let idleState={active:[],poses:[]};if(idleRuntime){scope.use(idleRuntime,'shore idle');group.add(idleRuntime.group);}
 let motionBindings=null,regroup=null,regroupStorage=null,regroupRecordIdentity=null,regroupSourcePlanSha256=null;if(regroupMode==='packed'){const {loadPackedRegroup}=await import('./regroup-plans.mjs'),loaded=await loadPackedRegroup(),{createRegroupController}=await import('./runtime/regroup-block-v1/controller.mjs');if(lateRegroup){const {createLateRegroupRecord}=await import('./late-regroup-plan.mjs'),{createLateRegroupController}=await import('./late-regroup-controller.mjs'),{createLateMotionBindings}=await import('./late-motion-bindings.mjs');const derived=createLateRegroupRecord(loaded.record,rosters);motionBindings=createLateMotionBindings(derived.units);regroup=createLateRegroupController(T,{ships,record:derived,planForRoute:loaded.planForRoute,landingDuration:timeline.duration,queueDuration:data.duration});}else regroup=createRegroupController(T,{ships,record:loaded.record,planForRoute:loaded.planForRoute,landingDuration:timeline.duration,queueDuration:data.duration});regroupStorage=loaded.stats;regroupRecordIdentity=loaded.recordIdentity;regroupSourcePlanSha256=loaded.record.sourcePlanSha256;}else if(regroupMode==='reference'){const base=new URL('./runtime/regroup-v1/',import.meta.url),manifest=await(await fetch(new URL('manifest.json',base))).json(),buffer=await(await fetch(new URL('plans.json',base))).arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',buffer)),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==manifest.plansSha256)throw Error('Regroup plan identity mismatch');const {createRegroupController}=await import('./runtime/regroup-block-v1/controller.mjs');regroup=createRegroupController(T,{ships,record:JSON.parse(new TextDecoder().decode(buffer)),landingDuration:timeline.duration,queueDuration:data.duration});}
 if(regroup)scope.use(regroup,'regroup controller');
 const formationRuntime=formationIdleMode==='gpu'?await createFormationIdlePlayback(T,human,ships.map(s=>({id:s.roster.id,actors:s.crew.actors.map(a=>s.roster.id+'/'+a.entry.id)})),record.source.sha256,regroupRecordIdentity,{poseTextures:resources.poseTextures,motionBindings}):null;let formationState={active:[],poses:[]};if(formationRuntime){scope.use(formationRuntime,'formation idle');group.add(formationRuntime.group);}
 let walkRuntime=null,lastViewRevision=-1;if(walkingMode==='hybrid'){const {createSharedWalkPlayback}=await import('./shared-walk.mjs');walkRuntime=await createSharedWalkPlayback(T,human,ships.flatMap(s=>s.crew.actors.map(a=>s.roster.id+'/'+a.entry.id)),record.source.sha256,regroupSourcePlanSha256,{poseTextures:resources.poseTextures,motionBindings,offscreenMode:walkingOffscreenMode});scope.use(walkRuntime,'marching playback');group.add(walkRuntime.group);}
 function update(time){if(!Number.isFinite(time)||time<0)throw Error('Invalid shore time');const viewRevision=walkRuntime?.roster.revision??0;if(time===lastTime&&viewRevision===lastViewRevision)return;lastTime=time;lastViewRevision=viewRevision;walkRuntime?.roster.beginFrame();const active=[],dirty=[],boatDirty=[];if(formationRuntime){formationState=formationRuntime.roster.sample(regroup.stats(time));formationRuntime.updateActorPoses(formationState.poses);}const formationSet=new Set(formationState.active);
  for(let index=0;index<ships.length;index++){
   const s=ships[index],state=regroup?.sample(s.roster.id,time),motionOwner=state&&state.phase!=='waiting'?'regroup':'landing';s.regroupState=state;if(s.motionOwner!==motionOwner){s.motionOwner=motionOwner;s.lastTime=null;for(const a of s.crew.actors)a.last=null;}const local=shoreTime(s.roster,time,timeline.duration);s.rigEvaluations=0;
   if(local!==s.lastTime){s.lastTime=local;const sequence=timeline.sample(local);s.last=sequence;s.frame.position.fromArray(s.roster.frame.position).add(new T.Vector3(...sequence.offset).applyQuaternion(s.frame.quaternion));s.frame.updateMatrixWorld(true);
    const rowing=rowingPlaybacks.get(s),result=rowing?rowing.handoff.update(sequence):s.crew.update(sequence);s.owner=result.owner??'cpu';s.counts=result.counts;s.rigEvaluations=result.rigEvaluations??result.dirty.length;
    dirty.push(...result.dirty.map(i=>s.start+i));copy(s.from,s.to);s.rendered.getObjectByName('BoardingPlankPivot').rotation.x=sequence.plankAngle;s.rendered.getObjectByName('BoardingPlankFold').rotation.x=sequence.plankFold;s.frame.updateMatrixWorld(true);boatDirty.push(index);
    if(rowing){rowing.runtime.group.visible=s.owner==='gpu';if(s.owner==='gpu')rowing.runtime.updateActorTransforms(s.crew.actors.map(a=>({id:a.entry.id,matrix:s.frame.matrixWorld})));}
   }
   if(s.owner==='cpu')for(let i=0;i<s.crew.actors.length;i++)active.push(s.start+i);
  }
  const regroupOwned=new Set();if(regroup)for(const s of ships)if(s.motionOwner==='regroup'){const changed=formationRuntime&&s.regroupState.phase==='formed'?[]:regroup.update(s,time,s.regroupState,{tryMarch:ctx=>walkRuntime?.roster.sample(ctx)??false});dirty.push(...changed);for(let i=0;i<s.crew.actors.length;i++)regroupOwned.add(s.start+i);s.counts={rowing:0,waiting:0,standing:0,aisle:0,walking:0,ashore:0,[s.regroupState.phase]:s.crew.actors.length};s.rigEvaluations+=changed.length;}
  walkRuntime?.finishFrame();
  if(idleMode!=='off'){
   idleState=idleRoster(rosters,data.actors,time,timeline.duration,data.duration);const keep=idleState.active.map((i,n)=>({i,pose:idleState.poses[n]})).filter(p=>!regroupOwned.has(p.i));idleState={active:keep.map(p=>p.i),poses:keep.map(p=>p.pose)};
   if(idleRuntime){idleRuntime.updateActorPoses(idleState.poses);}
   else for(let n=0;n<idleState.active.length;n++){const i=idleState.active[n];if(!idleReferences.has(i))idleReferences.set(i,createCrewShoreIdle(T,{root:actors[i].root}));idleReferences.get(i).sample(idleState.poses[n].time);dirty.push(i);}
  }
  const idleSet=new Set(idleRuntime?idleState.active:[]);activePoseIndices=active.filter(i=>!idleSet.has(i)&&!formationSet.has(i)&&!walkRuntime?.roster.has(i));for(const i of dirty){if(actorReaders)actorReaders[i].read(actorBounds[i],{worldUpdated:boundsMode==='synchronized'});else actorBounds[i].setFromObject(actors[i].root);actorBounds[i].applyMatrix4(frames[i]).expandByScalar(.001);poseDirty.add(i);}for(const i of boatDirty){if(shipReaders)shipReaders[i].read(shipBounds[i],{worldUpdated:boundsMode==='synchronized'});else shipBounds[i].setFromObject(ships[i].rendered);shipBounds[i].expandByScalar(.001);boatDirtySet.add(i);}
 }
 function applyVisibility(culler){if(walkRuntime)walkRuntime.setActive(walkRuntime.roster.active.filter(i=>!culler||culler.visible(walkRuntime.roster.actorBounds[i])));if(formationRuntime)formationRuntime.setActive(formationState.active.filter(i=>!culler||culler.visible(formationRuntime.actorBounds[i])));if(idleRuntime)idleRuntime.setActive(idleState.active.filter(i=>!culler||culler.visible(idleRuntime.actorBounds[i])));const active=activePoseIndices.filter(i=>!culler||culler.visible(actorBounds[i])),boatsActive=ships.map((_,i)=>i).filter(i=>!culler||culler.visible(shipBounds[i]));poses.update(active,[...poseDirty]);boats.update(boatsActive,[...boatDirtySet]);poseDirty.clear();boatDirtySet.clear();visibleActors=active.length;visibleShips=boatsActive.length;}
 update(0);applyVisibility(null);
 function actorStats(s){return s.crew.actors.map((a,i)=>({id:s.roster.actorIds?.[a.entry.id]??s.roster.id+'/'+a.entry.id,position:formationState.active.includes(s.start+i)?formationRuntime.positions[s.start+i].toArray():walkRuntime?.roster.has(s.start+i)?walkRuntime.roster.positions[s.start+i].toArray():(s.owner==='gpu'?s.seated[i]:a.root.position).clone().applyMatrix4(s.frame.matrixWorld).toArray()}));}
 return {group,update,applyVisibility,prepareView:(camera,width,height,shadow,options)=>walkRuntime?.roster.prepareView(camera,width,height,shadow,options),verifyBindings:poses.verifyBindings,duration:regroup?.duration??timeline.duration,stats(){const counts={};for(const s of ships)for(const [stage,n]of Object.entries(s.counts))counts[stage]=(counts[stage]??0)+n;return {arrival:true,dryShore:true,mode:'shore-fleet',poseMode,boundsMode,visibleActors,visibleShips,idle:{mode:idleMode,activeActors:idleState.active.length,ids:idleState.poses.map(p=>p.id),atlasBytes:idleRuntime?.atlasBytes??0,drawBatches:idleRuntime?.group.children.length??0,bindings:idleRuntime?.verifySelection(),cpuActors:activePoseIndices.length,primaryRowers:primary.owner==='gpu'?28:0,gpuRowers:ships.filter(s=>s.owner==='gpu').reduce((n,s)=>n+s.crew.actors.length,0),qualifiedCulling:Boolean(idleRuntime)},formationIdle:{mode:formationIdleMode,activeActors:formationState.active.length,bindings:formationRuntime?.verifySelection(),atlasBytes:formationRuntime?.atlasBytes??0},walking:{mode:walkingMode,...walkRuntime?.roster.stats(),atlasBytes:walkRuntime?.atlasBytes??0,bindings:walkRuntime?.verifySelection(),drawBatches:walkRuntime?.group.children.length??0,performanceQualification:false},regroup:{mode:regroupMode,storage:regroupStorage?.()??null,units:regroup?.stats(lastTime)??[],performanceQualification:false},sequence:primary.motionOwner==='regroup'?{...primary.last,phase:primary.regroupState.phase}:primary.last,placement:primary.frame.position.toArray(),frame:primary.roster.frame,time:lastTime,counts,actors:ships.flatMap(actorStats),ships:ships.map(s=>({id:s.roster.id,frame:s.roster.frame,placement:s.frame.position.toArray(),time:s.lastTime,owner:s.owner,counts:s.counts,rigEvaluations:s.rigEvaluations,actors:actorStats(s)})),partBatches:poses.partCount,shipBatches:boats.partCount,gpuPartBatches:[...rowingPlaybacks.values()].reduce((n,p)=>n+p.runtime.group.children.length,0),atlasBytes:bytes.byteLength,performanceQualification:false};},dispose:scope.close};
 }catch(error){return scope.fail(error);}
}
