/** Every visible scene string (SPEC 13.1): no coordinates or debug text reach the public HUD. */
export const GG_STRINGS = {
  pack: 'Loading the bridge and the Gate…',
  graphics: 'Starting graphics…',
  build: 'Building the scene…',
  firstFrame: 'Almost ready…',
  light: 'Light',
  flyovers: 'Flyovers',
  flyoverStop: 'Stop flyover',
  flyoverNeedsFog: 'Fog roll needs the Fog light',
  drive: 'Drive the sedan',
  leaveCar: 'Leave the car',
  controls: 'Controls',
  credits: 'Credits',
  resetView: 'Reset view',
  pauseMotion: 'Pause motion',
  resumeMotion: 'Resume motion',
  joystick: 'Drive and steer',
  boost: 'Boost', brake: 'Brake',
  turnAroundPrompt: 'End of the drive. Press R, or stop and hold S, to turn around',
  turnAroundTouch: 'End of the drive. Stop and hold the stick back to turn around',
  helpKeyboard: 'Drag to orbit, scroll or pinch to zoom, right-drag to pan. Choose a light and a flyover in the toolbar; any input ends a flyover. Press Enter or E, or choose Drive the sedan, to drive: W or Up accelerates, S or Down brakes and then reverses, A D or Left Right steer, Space brakes, X is the handbrake, and holding Shift boosts acceleration and top speed. At the end of the deck press R, or hold W against the stop or S at rest, to turn around. Drag to look around the car and scroll to bring the camera closer or farther. E or Escape leaves the car.',
  helpTouch: 'Drag to orbit, pinch to zoom, two-finger drag to pan; Reset view, in the toolbar, brings the camera back. Choose a light and a flyover in the toolbar; a touch ends a flyover. Choose Drive the sedan to drive with the stick: push it forward to accelerate, pull it back to brake and, once stopped, to reverse, and push it left or right to steer. Hold Boost for extra acceleration and speed; hold Brake to stop. Pinch to bring the camera closer or farther and drag to look around the car. At the end of the deck, stop and hold the stick back to turn around. Leave the car returns to the overview.',
  speed: (kmh: number) => `${Math.round(kmh)} km/h`,
} as const;
