import {createServer} from 'node:http';import {readFile,lstat,realpath} from 'node:fs/promises';import {dirname,resolve,extname,sep} from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath,pathToFileURL} from 'node:url';
const ROOT=resolve(dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(import.meta.url),MIME={'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.css':'text/css','.glb':'model/gltf-binary','.gz':'application/gzip','.bin':'application/octet-stream','.png':'image/png','.webp':'image/webp'};
export async function createTroyServer({root=ROOT}={}){
 root=resolve(root);const source=resolve(root,'web'),three=resolve(dirname(require.resolve('three')),'..'),pin=JSON.parse(await readFile(resolve(root,'runtime-pin.json'),'utf8')),current=JSON.parse(await readFile(resolve(root,'.runtime/current.json'),'utf8'));
 if(current.sha256!==pin.sha256||current.release!==pin.release||current.directory!==pin.release+'-'+pin.sha256.slice(0,12))throw Error('Run npm run hydrate for the current Troy runtime pin');const runtime=resolve(root,'.runtime',current.directory,'web');
 async function find(base,path){const file=resolve(base,path);if(!file.startsWith(base+sep))return null;try{if(!(await lstat(file)).isFile())return null;const physical=await realpath(file),physicalBase=await realpath(base);if(!physical.startsWith(physicalBase+sep))return null;return physical;}catch(error){if(error.code==='ENOENT')return null;throw error;}}
 return createServer(async(req,res)=>{try{const raw=new URL(req.url,'http://localhost').pathname,path=decodeURIComponent(raw);if(path.includes('\\')||path.includes('\u0000')||path.includes(':')||path.split('/').includes('..')){res.writeHead(400).end();return;}const vendor=path.startsWith('/vendor/three/'),relative=vendor?path.slice('/vendor/three/'.length):path==='/'?'index.html':path.slice(1),file=vendor?await find(three,relative):await find(source,relative)??(!/\.(mjs|js|html|css)$/.test(relative)?await find(runtime,relative):null);if(!file){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':MIME[extname(file)]??'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).end(await readFile(file));}catch(error){res.writeHead(500).end('Troy preview error');console.error(error);}});
}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const port=Number(process.env.TROY_PREVIEW_PORT||4421);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Valid Troy preview port required');const server=await createTroyServer();server.listen(port,'127.0.0.1',()=>console.log(`Troy source preview http://127.0.0.1:${port}/`));}
